/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Empleado;
import Clases.MiModeloTabla;
import Clases.MyIcono;
import javax.swing.JOptionPane;

/**
 *
 * @author alan
 */
public class FrmPlanillaEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form FrmPlanillaEmpleados
     */
    // La ventana principal esta compuesta de una ventana inferior
    private FrmNuevoEmpleado frmNuevo = new FrmNuevoEmpleado();
    public static MiModeloTabla modelo = new MiModeloTabla();
    
    public FrmPlanillaEmpleados() {
        initComponents();
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnNuevoEmp = new javax.swing.JButton();
        btnDelEmp = new javax.swing.JButton();
        btnModif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Bienvenido a la planilla de empleados");

        btnNuevoEmp.setText("Añadir Empleado");
        btnNuevoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEmpActionPerformed(evt);
            }
        });

        btnDelEmp.setText("Eliminar Empleado");
        btnDelEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelEmpActionPerformed(evt);
            }
        });

        btnModif.setText("Modificar Empleado");
        btnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnModif)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevoEmp)
                            .addGap(18, 18, 18)
                            .addComponent(btnDelEmp)
                            .addGap(42, 42, 42)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(129, 129, 129))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoEmp)
                    .addComponent(btnDelEmp)
                    .addComponent(btnModif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEmpActionPerformed
        // TODO add your handling code here:
        frmNuevo.setTitulo("Ingrese Datos de Empleado");
        frmNuevo.setVisible(true);
        frmNuevo.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnNuevoEmpActionPerformed

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifActionPerformed
        // TODO add your handling code here:
        
        // Se obtienen los nombres de todos los empleados
        String empleados[] = {"Juan", "Carlos", "Javier"};
        
        // Se lee Empleado a modificar
        MyIcono icono = new MyIcono();
        String nombre = (String)JOptionPane.showInputDialog(rootPane, "Empleado a modificar", "Selección", JOptionPane.DEFAULT_OPTION, icono, empleados, empleados[0]);
        if(nombre != null){
            frmNuevo.setTitulo("Modificando al empleado "+nombre);
            frmNuevo.setVisible(true);
            frmNuevo.modifica(nombre);
        }                
    }//GEN-LAST:event_btnModifActionPerformed

    private void btnDelEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelEmpActionPerformed
        // TODO add your handling code here:
        
        // Se obtienen los nombres de todos los empleados
        String empleados[] = {"Juan", "Carlos", "Javier"};
        
        // Se lee Empleado a modificar
        MyIcono icono = new MyIcono();
        String nombre = (String)JOptionPane.showInputDialog(rootPane, "Empleado a eliminar", "Selección", JOptionPane.DEFAULT_OPTION, icono, empleados, empleados[0]);
        if(nombre != null){
            // procedemos a eliminar 
            
            
            // una vez eliminado
            JOptionPane.showMessageDialog(rootPane, "Empleado eliminado correctamente");
        }          
    }//GEN-LAST:event_btnDelEmpActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelEmp;
    private javax.swing.JButton btnModif;
    private javax.swing.JButton btnNuevoEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
